modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="junk_jack_mc"
version="1.0.0"
displayName="Junk Jack MC"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Liam, MCreator"

[[dependencies.junk_jack_mc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



